<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>George Gally - Radarboy Broadcast</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="stylesheets/base.css">
	<link rel="stylesheet" href="stylesheets/skeleton.css">
	<link rel="stylesheet" href="stylesheets/layout.css">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body >

	<div class="back-header">

		<a href="index.html#broadcast">< Back</a>

	</div>


	<div class="container">

	<div class="sixteen columns add-bottom">
			<h2 class="remove-bottom add-top add-bottom">Radarboy Broadcast</h2>
			<h4>Website. Entertainment hub.</h4>

	</div>

	<div class="two-thirds column">

<img src="images/broadcast1a.jpg" width="100%"> <br>
<img src="images/broadcast1b.jpg" width="100%"> <br>
<img src="images/broadcast1i.jpg" width="100%"> <br>
<img src="images/broadcast1f.jpg" width="100%"> <br>
<img src="images/broadcast1e.jpg" width="100%"> <br>
<img src="images/broadcast1c.jpg" width="100%"> <br>
<!-- <img src="images/broadcast1d.jpg" width="100%"> <br> -->


<!-- <img src="images/broadcast1g.jpg" width="100%"> <br> -->
<img src="images/broadcast1h.jpg" width="100%"> <br>


</div>

<div class="one-third column">
<p>
	Based on the metaphor of a TV station, Radarboy Broadcast was a content and entertainment hub, consiting of quirky and humurous experiments, games and documentary-type digital content. <br><br>
	Content changed daily, pulled from an every growing pool of artworks, generated by myself and radarboy partner, Gareth.
</p>

<p>
	<b>Grunt Chat </b><br>
I love using technologies for what they're not meant for. <b>Grunt Chat </b> was an alternative chat engine where users can only chat in "monkey speak". No real point. Just loved the idea of grunting to people on the other side of the world.
</p>

<p>
<b>Show &amp; Tell</b><br>
A classic show and tell. Bring emphemera from home on Monday morning and build a content around them.</b>
</p>


<p>
	<b>People of the South</b><br>
There are so many interesting characters floating around Cape Town. We wanted to capture, conduct short interviews and allow them to say their piece to the world.
</p>



<p>
<b>Experimental Lab</b><br>
Mythbusters before Mythbusters. We put "old wives tales" to the tests, with clasic experiments like <b>"Tooth vs Nail"</b> - who'll survive being submerged into Coke over time and <b>"The Rotting Burger Challenge"</b>
</p>

<p>
<b>Words of Advice for Young People</b><br>
Tips and tricks to survive live in Cape Town - whether it being <b>"How to build your own wheelclamp"</b>, where to find the best old school coffe houses, taxi etiquette and more.
</p>




Creative Direction. Concept, design, programming <br>
Technologies: PHP, MySql, Flash<br>
Medium: Online


</div>


	</div><!-- container -->


	<?php include("footer.php"); ?>
	<?php include("tracker.php"); ?>



<!-- End Document
================================================== -->
</body>
</html>
