<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>George Gally - Radarboy Broadcast</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="css/Skeleton.css">
	<link rel="stylesheet" href="css/style.css">


	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body >

	<div class="back-header">

		<a href="index.php#broadcast">< Back</a>

	</div>


	<div class="container">

	<div class="sixteen columns half-top add-bottom">
			<h1>Radarboy Broadcast</h1>
			Website. Entertainment hub.

	</div>

	<div class="sixteen columns">

<img src="images/broadcast1a.jpg" width="100%"> <br>

</div>

<div class="two-thirds column half-top half-bottom">
<p>
	Based on the metaphor of a TV station, <b>Radarboy Broadcast</b> was a content and entertainment re-imagined portal, consiting of quirky and humurous experiments, games and documentary-type digital content. <br><br>
	Content changed daily, pulled from an every growing pool of artworks, generated by myself and radarboy partner, Gareth.
</p>


</div>

<div class="sixteen columns">
<img src="images/broadcast1b.jpg" width="100%"> <br>
</div>

<div class="two-thirds column half-top half-bottom">
	<p>
	<b>Experimental Lab</b><br>
	Mythbusters before Mythbusters. We put "old wives tales" to the test, with clasic experiments like <b>"Tooth vs Nail"</b> - who'll survive being submerged into Coke over time and <b>"The Rotting Burger Challenge"</b>
	</p>

</div>

<div class="sixteen columns">
<img src="images/broadcast1i.jpg" width="100%"> <br>
</div>

<div class="two-thirds column half-top half-bottom">
<p>
	<b>Grunt Chat </b><br>
I love using technologies for what they're not meant for. <b>Grunt Chat </b> was an alternative chat engine where users can only chat in "monkey speak". No real point. Just liked the idea of grunting to people on the other side of the world.
</p>

</div>

<div class="sixteen columns">
<img src="images/broadcast1f.jpg" width="100%"> <br>
</div>

<div class="two-thirds column half-top half-bottom">
	<p>
	<b>Show &amp; Tell</b><br>
	A classic show and tell. Bring emphemera from home on Monday morning and build a content around them.</b>
	</p>

</div>

<div class="sixteen columns">
<!-- <img src="images/broadcast1e.jpg" width="100%"> <br> -->
<img src="images/broadcast1c.jpg" width="100%"> <br>
<img src="images/broadcast1d.jpg" width="100%"> <br>
</div>

<div class="two-thirds column half-top half-bottom">
	<p>
		<b>People of the South</b><br>
	There are so many interesting characters floating around Cape Town. We wanted to capture, conduct short interviews and allow them to say their piece to the world.
	</p>


</div>





<div class="sixteen columns">
<!-- <img src="images/broadcast1g.jpg" width="100%"> <br> -->
<img src="images/broadcast1h.jpg" width="100%"> <br>
</div>

<br>
<div class="two-thirds column half-top half-bottom">
<p>
	<b>Mark Shuttleworth</b><br>
		A made up conversation with the first African in space
</p>

</div>


<div class="row">

	<div class="two-thirds column half-top">

	<!-- <p>
	<b>Words of Advice for Young People</b><br>
	Tips and tricks to survive live in Cape Town - whether it being <b>"How to build your own wheelclamp"</b>, where to find the best old school coffe houses, taxi etiquette and more.
	</p> -->


	In collaboration with Gareth Chisholm.<br>
	Technologies: PHP, MySql, Flash<br>

	</div>

</div>

<p class="add-top add-bottom center">
		<a href="looktosky.php">Next ></a>
</p>

	</div><!-- container -->


	<?php include("footer.php"); ?>
	<?php include("tracker.php"); ?>



<!-- End Document
================================================== -->
</body>
</html>
